services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PINECONE_API_KEY=pcsk_AoQGh_L4aL5pgM5QVjvvMALcys5S5868NeJYzwpZru5U5DRFEwwTWbUFnMZLiwtESvGT3


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend